name: Add contributors

on:
  schedule:
    - cron: "20 20 * * *" # Runs every day at 20:20 UTC
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  add-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update contributors
        uses: BobAnkh/add-contributors@master
        with:
          CONTRIBUTOR: "### Contributors"
          COLUMN_PER_ROW: "6"
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMG_WIDTH: "100"
          FONT_SIZE: "14"
          PATH: "/README.md"
          COMMIT_MESSAGE: "docs(README): update contributors"
          AVATAR_SHAPE: "round"

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add README.md
          git commit -m "docs(README): update contributors" || echo "No changes to commit"
          git push origin main
